### ISSUE TITLE
Reprendre composer.json

### ISSUE THREAD

**Issue by mattgu74** [payutc/onyx#12]
Le fichier est au nom de symfony avec une licence MIT, faudrais adapter ça au projet onyx ;)

**Comment by mattgu74** [comment]
Au passage pensé à supprimer `composer.phar` et `composer.lock` qui n'ont pas à être versionné.

**Comment by flo-sch** [comment]
Tiens d'ailleurs y a un moyen de supprimer toutes les versions d'un fichier sans supprimer le fichier local ?
Ou faut supprimer le fichier, commiter, éditer le gitignore et se remettre le fichier en local ?

**Comment by trecouvr** [comment]
Je crois pas, fais une sauvegarde, puis `git rm`, modification du `.gitignore`, commit, push, et restauration de la sauvagarde

**Comment by flo-sch** [comment]
Okay merci :)

**Comment by mattgu74** [comment]
L'issue n'est pas terminé, j'ai fais une partie du nettoyage, mais il en reste encore à faire.

**Comment by flo-sch** [comment]
cf PR #40
