### ISSUE TITLE
Accueil: Liste des events à venir

### ISSUE THREAD

**Issue by mattgu74** [payutc/onyx#13]
Sur la page d'accueil je veux voir la liste des events à venir.

**Comment by mattgu74** [comment]
@Flo-Schield-Bobby tu t'en occupes après avoir mergé ma PR, je vois que tu n'as plus de tache assigné ?

**Comment by flo-sch** [comment]
Haha j'aurai pas du bossé...

**Comment by mattgu74** [comment]
^^ Mais si faut qu'on avance ;)

**Comment by flo-sch** [comment]
Done in PR #24
