### ISSUE TITLE
Ajouter un champ "seller"

### ISSUE THREAD

**Issue by mattgu74** [payutc/onyx#16]
Dans le cas ou les billets sont vendus "physiquement" ou via l'interface d'administration, il est important de savoir qui à réalisé la vente (qui était authentifié sur l'interface).

Pour des raisons de traçabilités, surtout si un jour on ajoute un module permettant de vendre des places "physiquement".

**Comment by flo-sch** [comment]
Un champ texte du coup ?

**Comment by mattgu74** [comment]
Non un lien vers un user.

**Comment by mattgu74** [comment]
Mais y'a pas d'urgence sur cette issue ;)

**Comment by flo-sch** [comment]
Spas grave ça prend 10 secondes.
Petite question par contre, je pars de quelle branche pour la corriger ?
CRUD - admin ?

Parce que je n'ai rien mergé du coup pour le moment ?!
Ou j'attends un peu justement ?

**Comment by mattgu74** [comment]
Et bien maintenant que j'ai merge sur le repo principal.
Il faut que sur ton ordi en local, tu fasses:
git co master # tu te mets dans ta branche master local
git pull payutc master #j'assume que dans .git/config, tu as un "remote
payutc"

# ça va te pull le dernier état de la branche master du dépot principal en

local
git push origin master # ça pushera le merge qui a été fait dans la branche
master du dépot principal vers ton dépot perso sur github

## 

Matthieu GUFFROY

2014/1/3 Florent SCHILDKNECHT notifications@github.com

**Comment by flo-sch** [comment]
Okay super ! Je corrige tout de suite sur une nouvelle branche du coup.
Et comment proposer une PR pour cette issue direct, plutôt que de dupliquer comme les autres ?

**Comment by mattgu74** [comment]
Tu ne peux pas, il en faut pas le voir comme une duplication.
Une PR, certes ça crée une issue, mais faut vori cette issue, comme une
nouvelle tache qui consiste à la relecture d'un morceau de code.

Alors que les issues sont vraiment des choses à implémenter ou des bugs à
corriger. Une issue "PR", peut corriger plusieurs issues "normal" en même
temps.

## 

Matthieu GUFFROY

Le 3 janvier 2014 14:38, Florent SCHILDKNECHT notifications@github.com a
écrit :
