### ISSUE TITLE
Retirer la configuration en dur

### ISSUE THREAD

**Issue by mattgu74** [payutc/onyx#18]
Dans la PR #17, il y'a de nombreuses variables qui sont fixés en dur.
Url du CAS et URL de Ginger (+clef de ginger)

Il est important de déplacer ces variables dans la config.

**Comment by flo-sch** [comment]
Okay :)

Pour info, on va utiliser un fichier de config propre au bundle !
Si ça vous intéresse : http://www.squareeyes.fr/actualite/jouer-avec-les-variables-globales-dans-symfony-2

**Comment by flo-sch** [comment]
cf PR #32

**Comment by flo-sch** [comment]
On peut fermer du coup ?
