### ISSUE TITLE
Generation mot de passe

### ISSUE THREAD

**Issue by mattgu74** [payutc/onyx#19]
Lorsqu'un utilisateur est crée via une authentification CAS. On lui crée un mot de passe "de secours".

Actuellement ce mot de passe est tout simplement son login, on ne peut pas mettre en production tant que c'est comme ça.

**Comment by flo-sch** [comment]
D'ac, c'est un blocage externe à Onyx du coup ça ?

**Comment by mattgu74** [comment]
Non non, c'est dans ma PR en attente d'acceptation.

**Comment by flo-sch** [comment]
Tu veux juste que je génère un truc aléatoire ?
Je m'en occupe stu veux !

**Comment by mattgu74** [comment]
Si tu as la fonction sous la main oui vas y.

**Comment by flo-sch** [comment]
Bon je l'ai corrigé mais j'ai un peu merdé le versionning :
En fait j'ai besoin de fichiers (pour l'envoi du mail) de la PR #25 qui n'a pas encore été mergé.

Du coup je me suis basé sur cette branche là, et j'en ai créé une nouvelle pour la modif.
Mais j'ai oublié le checkout avant de commencer à bosser...
Du coup j'ai commit sur la branche de la PR #25, j'ai checkout sur ma nouvelle branche et j'ai mergé celle de la #25...

Comment je répare ça ?
J'attends qu'on merge ?

Parce que du coup si je propose une nouvelle PR maintenant, elle va dupliquer les commits de la PR #25...

**Comment by mattgu74** [comment]
C'est pas grave, si les commits en question ont autant leur place dans une
PR que dans l'autre... il seront acceptés avec la première PR, GIT sait que
c'est les mêmes et il se remettra à niveau pour la deuxième PR.

## 

Matthieu GUFFROY

Le 9 janvier 2014 19:28, Florent SCHILDKNECHT notifications@github.com a
écrit :

**Comment by mattgu74** [comment]
Resolu par #27
