### ISSUE TITLE
Envoi de mail lors de la création d'un user.

### ISSUE THREAD

**Issue by mattgu74** [payutc/onyx#20]
Lorsque l'on crée un utilisateur, il faut lui envoyer son mot de passe par mail.
(Et bien s'assurer que c'est un mot de passe généré)

De cette manière ça permet de vérifier que l'adresse mail lui appartient bien.

**Comment by flo-sch** [comment]
Symfony par défaut inclut Swiftmailer qui permet d'envoyer des mails de plusieurs manières, je ne l'ai utilisé qu'avec un compte gmail lié, par SMTP, mais c'est super long à l'envoi (plusieurs secondes), je pense qu'il vaut mieux passer par un serveur mail local, en prod... Je peux toujours déjà mettre le code de l'envoi, et on verra après comment on gère ça.

Une bonne solution est de stocker les mails à envoyer dans une sorte de todolist pour un CRON toutes les X minutes, et facile à mettre en place avec SM.

**Comment by mattgu74** [comment]
+1 pour le smtp, y'a aucun soucis il y'en a un de disponible sur le serveur des assos.
+1 pour le cron et la sorte de todolist.

**Comment by flo-sch** [comment]
Référence : PR #25

**Comment by mattgu74** [comment]
Cette issue à été résolu dans le fond par #25, mais la partie "validation de l'adresse mail" n'a pas été faite. Du coup j'ouvre une nouvelle issue pour ça (#29)
