### ISSUE TITLE
Authentification pour l'interface d'Admin

### ISSUE THREAD

**Issue by mattgu74** [payutc/onyx#23]
Pour l'interface d'Admin l'authentification est très proche de celle utilisé pour l'interface "user" qui utilise le CAS.

Sauf que dans ce cas la, c'est à payutc de valider le ticket CAS, vu que l'on doit s'authentifier au passage auprès du CAS, qui permet de nous donner les droits de l'user (sur les fundations (= assos))

**Comment by flo-sch** [comment]
T'as l'air chaud la-dessus, je te laisse gérer ?

**Comment by mattgu74** [comment]
Oui je me suis assigné ;) 

Mais d'abord faut s'occuper de rendre le payutc-json-client sous forme composer, (c'est un autre repo de l'organisation payutc. Il y'a @trecouvr qui est assigné à cette tache, mais il semblerait qu' @apuyou  puisse la régler d'ici la fin du weekend)

**Comment by flo-sch** [comment]
NB : ça m'intéresse de comprendre comment publier un bundle ou autre via composer, vous passez par packagist ?

**Comment by mattgu74** [comment]
Regarde dans la PR en attente, comment j'appelle le Ginger-Client. 
Dans le cas présent, je me contente d'aller le chercher sur github en donnant l'adresse, composer sait gérer ça aussi.
