### ISSUE TITLE
Vérification des adresses mails

### ISSUE THREAD

**Issue by mattgu74** [payutc/onyx#29]
L'utilisateur doit valider son adresse mail en cliquant sur un lien reçu par mail.

Car l'adresse mail permet d'identifier l'école de provenance et parfois de distinguer certains groupes d'utilisateurs et donc de tarifs.

De plus les billets seront envoyés par mail, il faut donc que l'ont vérifie que l'utilisateur reçoive bien nos mails.

**Comment by flo-sch** [comment]
Attention on a pas encore de confirmation de mail il me semble !

**Comment by mattgu74** [comment]
C'est bien pour ça que j'ai ouvert cette issue ;)

**Comment by flo-sch** [comment]
Ah pardon OK j'ai vu le closed de la PR 20 et je l'ai confondu avec celle là du coup !
Est-ce qu'on doit de notre côté faire un traitement sur l'email ?
Ou c'est juste une vérification générale ?

**Comment by mattgu74** [comment]
Et bien on doit lors du mail, insérer un token dedans. Et mettre le status de l'user a un truc genre "unvalidated", et au retour du token changer le status.

Une autre méthode plus simpe, consiste à ne pas laisser l'utilisateur choisir son mot de passe et le lui envoyer par mail. (C'est moins sécurisé, c'est vrai... Mais bon je n'estime pas que ce soit critique, en plus on peut faire un truc pour changer son mot de passe à la première connexion si ce problème de sécurité nous tient vraiment à coeur).

**Comment by flo-sch** [comment]
cf PR #35

**Comment by flo-sch** [comment]
On peut fermer aussi ?
