### ISSUE TITLE
Créer la page d'un event

### ISSUE THREAD

**Issue by mattgu74** [payutc/onyx#30]
Pour un event donné il faut : 
- Le bandeau "header" (ou un bandeau par défaut)
- L'image de description
- Le texte descriptif + le titre + les dates clairement
- Une sous zone, avec "mes places" (ou si je ne suis pas connecté, un bouton m'invitant à me connecter pour voir mes places achetés + les tarifs spéciaux)
- Une sous zone avec les différents tarifs dispo, et un bouton "Réserver"

**Comment by flo-sch** [comment]
Okay c'est du front, c'est pour moi :)

**Comment by flo-sch** [comment]
cf #34 

--> Je ne sais pas trop comment gérer l'achat d'une place par contre ; J'ai laissé un lien non-fonctionnel pour la réservation pour le moment.
