### ISSUE TITLE
Set up datagrid.js for back-end listings

### ISSUE THREAD

**Issue by flo-sch** [payutc/onyx#43]
On risque potentiellement de se prendre un problème d'UI de taille du listing dans le Back-Office, à partir du moment où on commencera à avoir pas mal d'évènements, de tarifs ou d'utilisateurs... Mais surtout de tickets : ça peut être super pratique pour une vérifier instantanément si un mec à bien un ticket ou non sans avoir besoin de ses identifiants !
Je voudrais tenter une petite solution qui n'a pas l'air trop complexe :

<a href='http://exacttarget.github.io/fuelux/#datagrid' target='_blank'>Datagrid</a> est un plugin bootstrap de Fuel UX permettant de trier et paginer un tableau, et ajoute un moteur de recherche.
Il nécessite un petit export <a href='http://api.symfony.com/master/Symfony/Component/HttpFoundation/JsonResponse.html' target='_blank'>JSON</a> des données.

<a href='http://dailyjs.com/2012/10/29/fuel-ux/'>dailyJs : Charger une dataSource asynchrone</a>

**Comment by mattgu74** [comment]
Pour les événements, vu qu'il seront pré-flitré par assos (enfin les droits que tu as dans l'admin) je ne pense pas que ce sera un problème (ou pas avant au moins 10semestres... nos successeurs auront le temps de voir).

Pour les tarifs, je pense qu'il faudrait retirer la possibilité d'afficher la liste compléte, mais mettre un bouton depuis les events pour accèder à la liste des tarifs d'un event donné.

Pour les tickets, idem il faut y venir depuis un event en particulier pour pas tout mélanger. De plus je pense que c'est une connerie d'afficher la liste en entière, il faudrait mettre une recherche par utilisateur. (A la limite la ton plugin pourrait bien passer).

Pour les utilisateurs, c'est une page réservé aux super-admins et j'espere qu'elle ne servira quasiment jamais... Donc a le temps de voir venir.

**Comment by flo-sch** [comment]
Ouais en fait c'est aussi pour mettre en avant le fait que le listing du CRUD basique de Symfony2 est pas forcément le mieux pour nos entités.

C'est une piste, mais effectivement il faut déjà réfléchir en terme de données avant de changer l'UI !

En vrai ce projet me sert aussi de test d'interface à la fois front et back, et j'ai revu passé ce plugin donc je me dis que ça pouvait être une bonne idée.

Faut juste qu'on prenne d'abord une décision de ce qu'on affiche et avec quels droits !
Et déjà que je comprenne comment marchent réellement les droits ^^

Après comme tu le dis, ce n'est pas prioritaire du tout !

**Comment by mattgu74** [comment]
Oép focalise toi sur le "front" et les issues que je viens d'ouvrir pour le moment. (On va éviter les merges foireux dans l'admin et a priori mon taff du moment est dans l'admin ^^)
